defaults:
  - seed: seed_42
  - data: train_test/dataset  
  - imputation_method: dummy_value
  - model: tempo/leak_test_data
  - _self_

# Hydra
hydra:
  run:
    dir: ./output/hydra

# Use SLURM_ARRAY_TASK_ID to index `data`
task_id: ???

# 32-bit floating point precision for torch 
precision: medium

# Load list of dataset cfgs and use SLURM_ARRAY_TASK_ID to index the list
gift_split: train_test
dataset_name: ${data[${task_id}].name}
term: ${data[${task_id}].term}

# Batch size for evaluation 
batch_size: 256



