defaults:
  - logging: timestamp
  - data: dataset # List of dataset name-term pairs 
  - imputation: dummy_value
  - _self_

# Redirect hydra output
hydra:
  run:
    dir: ./output/hydra

# Seed for reproducibility
seed: 42
workers: true
verbose: true

# Set floating point precision for PyTorch
precision: highest

# Batch size for evaluation
batch_size: 128

# Ensemble configuration
ensemble:
  metric: mae
  n_windows: 1
  batch_size: $batch_size
